### ISSUE TITLE
Preserve article order

### ISSUE THREAD

**Issue by Lodifice** [Lodifice/mfnf-pdf-export#1]
While the tree-like filesystem structure is elegant to store articles, it has the drawback that all files are sorted alphabetically. To solve this problem, I can think of two possibilities:

1. Internal book-keeping - store a table of contents file
2. renaming - prepend the position to the file name

Currently, I prefer option 1. Any opinions?

**Comment by kulla** [comment]
I guess this issue is obsolete in our current implementation. I close it

@Lodifice Please reopen this issue in case I oversee something...
