### ISSUE TITLE
Fix parsing of equations

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#10]
Some `{{Formel|....}}` aren't parsed properly. This bug seem to be present for equations inside a box like in the code

    {{:Mathe für Nicht-Freaks: Vorlage:Definition
       |definition={{Formel|<math>x^2</math>}}
    }}

**Comment by vroland** [comment]
fixed in c29fc3f032ba13eec38bdfb165277c9b710a1c03.
