### ISSUE TITLE
design: Part title pages, mini change

### ISSUE THREAD

**Issue by elbotho** [Lodifice/mfnf-pdf-export#100]
Following my design mockup in #97 the "Teil 1" should also be in 9pt.
Is that possible?

---
![image](https://user-images.githubusercontent.com/1258870/31761368-e27a79d8-b4b7-11e7-961c-0a6c0196c9a7.png)

**Comment by Lodifice** [comment]
Of course, done in d85b2f6 ;)

However, the part prefix looks much smaller compared to the actual part than in your design. Can you please check that? (If everything is fine, just close the issue.)
