### ISSUE TITLE
Icons for semantic boxes: use vector graphics?

### ISSUE THREAD

**Issue by elbotho** [Lodifice/mfnf-pdf-export#101]
Icons would render a bit nicer (on screens) so we should use vector graphics for the icons in the long term. 
@Lodifice Should I provide them as PDF or SVG?

**Examples** of not so nice rendering below:
(first: blurry, second: weird black contour)

----
![image](https://user-images.githubusercontent.com/1258870/31814574-60f25d8a-b58a-11e7-93dc-76f5199b2185.png)
![image](https://user-images.githubusercontent.com/1258870/31814600-75abacae-b58a-11e7-89a5-8f2e8b8ef56d.png)

**Comment by elbotho** [comment]
If I remember correctly we decided on using pdfs directly as image format, right?

**Comment by Lodifice** [comment]
Not necessarily, as we have to use inkscape for converting some SVGs to PDF anyway, you can provide SVG or any vector format inkscape understands ;)

**Comment by Lodifice** [comment]
Following your commit, I have switched from using the pngs to pdfs in 3d039df. Do you observe improvements?

**Comment by elbotho** [comment]
Way better on first glance. Thanks!
