### ISSUE TITLE
Character encoding problem in PDF-TOC

### ISSUE THREAD

**Issue by elbotho** [Lodifice/mfnf-pdf-export#106]
Looks like there is a character encoding problem in the exported PDF.
In at least 2 different viewers on a Mac.
Any ideas?

**Example**

---
![bildschirmfoto 2017-10-26 um 18 55 44](https://user-images.githubusercontent.com/1258870/32071859-f0ba1b14-ba90-11e7-9068-c97fc45ff564.png)
---

**Comment by svenpruefer** [comment]
Ich habe das Problem auch sowohl unter Windows als auch unter Linux unter mehreren PDF-Viewern. Benutzt ihr hyperref? Dafür gibt es die Option unicode bzw. pdfencoding=auto, die mehr Symbole erlauben. Ihr könnt auch noch texorpdfstring versuchen, wie in dem Beispiel

\section{My super awesome title \texorpdfstring{A}{B}}

Jetzt wird A im Text in der Überschrift verwendet, kann also insbesondere Mathemodus beinhalten, und B wird in den Bookmarks verwendet. Also wäre zumindest

\section{Teilfolgen, \texorpdfstring{Häufungspunkte}{Haeufungspunkte} und Cauchyfolgen}

eine (wenn auch doofe) Lösung. Und/oder eben \usepackage[unicode]{hyperref} in der Präambel.
