### ISSUE TITLE
Make sure first part page is always on the right side

### ISSUE THREAD

**Issue by elbotho** [Lodifice/mfnf-pdf-export#107]
Is there an automatic way to make sure that the first part page (after the TOC) is always on the right side (inserting a blank page if needed)?

Currently we would need a blank page, but the length of the TOC could change later.

**Comment by Lodifice** [comment]
This is already built in. Parts always start on an odd page, the current blank page between TOC and first part is added automatically. If you e.g. remove an included page (`pages=1-7` in `includepdf`), the blank page is automatically removed.

**Comment by elbotho** [comment]
I see, I guess this expects a single cover page as first page, right?
Atm I provide no cover as this usually provided to the printer as a second pdf.

**Comment by elbotho** [comment]
sorry for the confusion.
I was confused and everything should be fine with 797e1c9834d2ab298573c21d595092f66a7b9f48
