### ISSUE TITLE
Image gets exported twice

### ISSUE THREAD

**Issue by matipau** [Lodifice/mfnf-pdf-export#109]
In the article "Teleskopsumme und Teleskopreihe", the file Teleskop.svg appears two times as a figure on two subsequent pages in the exported PDF (and also two times in the list of figures), although it is included only once in the article. I have no clue why this "cloning" happens...

**Comment by Lodifice** [comment]
Teleskop.svg appears twice and Englisches_Marineteleskop_von_Karl_Friedrich_Neumann,_item_2.jpg does not appear at all. I think it is a bug which leads to floating figures overwriting their successors. Any ideas

**Comment by vroland** [comment]
This may relate to thumbnail figures beeing moved to the closest heading...

**Comment by Lodifice** [comment]
Yes, it does. After parsing, the tree ist still correct. After the MoveThumbnailImages class has been executed, the tree contains the duplicates. @vroland you have introduced that code in be66c8f8, can you please check?
