### ISSUE TITLE
print preparation: color space 

### ISSUE THREAD

**Issue by elbotho** [Lodifice/mfnf-pdf-export#110]
We talk about it some time, but does some one know how hard it is to use cmyk colors in latex?

**Comment by Lodifice** [comment]
Yes, it is already a feature of `xcolor`, look [here](https://en.wikibooks.org/wiki/LaTeX/Colors#Color_Models).

**Comment by elbotho** [comment]
Closed in ef6d5a2cba4d26d877326788ca50ca71889c76c3
