### ISSUE TITLE
Check attribution of karmilla

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#112]
The font https://github.com/ms-studio/karmilla/ is published under OFL. We need to check we fulfill the requirements of this license (especially the attribution requirements).

**Comment by elbotho** [comment]
According to http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=FontFAQ_use we are fine.

**Comment by elbotho** [comment]
I think this can be closed.
