### ISSUE TITLE
LaTeX-Error at page 89

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#116]

**Comment by kulla** [comment]
![screenshot from 2017-12-31 13-42-45](https://user-images.githubusercontent.com/1327215/34461666-af13d334-ee30-11e7-9441-1e142ab44b92.png)

**Comment by vroland** [comment]
Ah, this is on page 99 for me...
The problem seems to be an inline align*-environment... But I have no idea why it renders it like this. Putting this formula in a new paragraph would solve this.

**Comment by kulla** [comment]
There was an equation inside a paragraph. [I have corrected it](https://de.wikibooks.org/w/index.php?title=Mathe_f%C3%BCr_Nicht-Freaks%3A_Grenzwerts%C3%A4tze%3A_Grenzwert_von_Folgen_berechnen&action=historysubmit&type=revision&diff=835453&oldid=831979). Lets see whether it is fixed in the next build...
