### ISSUE TITLE
Add cover to mfnf_epilogue.pdf and mfnf_prelude.pdf

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#117]
The cover of the book should be added to the predefined PDF so that the final PDF of https://mathe-builds.serlo.org/analysis1_final/analysis1_final.pdf has a cover.

(The print version will be changed manually anyways)

**Comment by elbotho** [comment]
Closed by 32bcfedf4e64947cf16529d328ed25706dae2cbb.

> **updated predesigned pages**
> - now include cover
> - hyperlinks now work in imprint and logos etc.
>
