### ISSUE TITLE
Create PDF pages for fundraising and participation calls

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#118]
We need to include pages for participation and fundraising calls. They should be 2 pages and shall be stored here: https://github.com/Lodifice/mfnf-pdf-export/tree/master/predesigned_pages

**Comment by SimonKoehl** [comment]
The pages could be included in the PDF more than once - preferably after an important/poppular chapter(s)

**Comment by elbotho** [comment]
@kulla 
I added:
- `mfnf_ fundraising.pdf`
- `mfnf_ participation.pdf`

removed page trim again (see #99)

**Comment by kulla** [comment]
thanks @elbotho
