### ISSUE TITLE
Include participation and fundraising calls in the final PDF

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#119]
After #118 – More than once and after popular chapters

**Comment by elbotho** [comment]
@SimonKoehl more than twice feels a bit pushy, especially since it's a whole page. What do you think? 
@kulla what do you think about using for example the question template to place a little participation-reminder at the end of an chapter?

**Comment by kulla** [comment]
@elbotho We currently have 3 participation and fundraising calls I guess they will be enough. Let's keep the reminder at the end in mind.
