### ISSUE TITLE
Parsing of references

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#12]
References with the code `<ref>...</ref>` need to be properly parsed. In the first version these elements can be ignored in the final PDF.

**Comment by Lodifice** [comment]
Parsing implemented in 50af2d4505688d209f43cceb0b6e8de51befbb4c. @kulla, do you have an idea where the actual references get lost in the parsing process? They are an `unordered list` at the end of the html body, but when lists are handled, they are already gone.

**Comment by kulla** [comment]
The ordered list is stored in the footer which is delete at the end of the parsing process. I thought that the body of an reference is stored where the reference occurs. Unfortunately this is not the case. I guess implementing a proper parsing is hard currently and since we do not show references in the first version of the PDF we can implement a proper parsing later. Thus with https://github.com/Lodifice/mfnf-pdf-export/commit/7a29a2050fd8bd88cafe312263691f095baef11c references are just deleted. With #24 we can track the issue of a proper parsing. IMHO the now found is sufficient.
