### ISSUE TITLE
Different versions for print and online publication

### ISSUE THREAD

**Issue by elbotho** [Lodifice/mfnf-pdf-export#120]
I suggest at least **two versions**:
- for print (current version)
- for digital publication (pdf)
- maybe even a version optimized for self-printing

suggestions for **digital publication pdf**:
- [ ] maybe rgb colors again
- [ ] different prelude and epilogue versions (including cover e.g.)
- [ ] a way to display links and videos ( see #23)
- [ ] no page trim
- [ ] different  format for screen display? (#114, #60)

**Comment by elbotho** [comment]
own repro for lmu print version:
https://github.com/kulla/mfnf-analysis1-lmu-print2018

**Comment by vroland** [comment]
still applies to new toolchain, but should be discussed in a new issue.
