### ISSUE TITLE
Parsing of headings in MediaWiki changed

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#121]
The parsing of headings with non ASCII characters changed. For example `== Übungsaufgaben ==` is now parsed to

    <h2 id="Übungsaufgabe"><span id=".C3.9Cbungsaufgabe" typeof="mw:FallbackId"></span> Übungsaufgabe </h2>

Because of this we have two bugs

- [x] The `<span id="..." typeof="mw:FallbackId">` needs to be removed from the html
- [x] The excluding of some headings does not work any more

**Comment by vroland** [comment]
Argh, this is why we need our own parser :P

**Comment by vroland** [comment]
should be fixed now.

**Comment by Lodifice** [comment]
So the typo fix (1d60509b3065a49c85a874c109260fb63b6c9fe7) solved the problem that sections were not excluded anymore?

**Comment by vroland** [comment]
As far as I can tell.. The example book looks correct to me.
