### ISSUE TITLE
Link https://mathe-builds.serlo.org/downloads/... resolves into 414

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#122]
Having a link like https://mathe-builds.serlo.org/downloads/analysis1/analysis1.pdf resolves into `414 Request-URI Too Large` since it is resolved into something like

    https://mathe-builds.serlo.org/downloads/analysis1/s/analysis1/s/analysis1/s/analysis1/s/analysis1/s/analysis1/s/analysis1/s/analysis1/s/analysis1/s/analysis1/s/analysis1/s/analysis1/s/analysis1/...

There should be a `404 response`

**Comment by vroland** [comment]
should be fixed now.
