### ISSUE TITLE
Fundraising and partician calls mess with the page number?

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#123]
Are the page number and the layout of the pages with the included participation and fundraising calls handled well?

**Comment by Lodifice** [comment]
What exactly do you mean by mess? For example, in the [current build](https://mathe-builds.serlo.org/analysis1_final/analysis1_final.pdf) (well, of course until 3 am), look at pages 85 to 87. The chapter ends at a page numbered 85, then you have the participation call and the next chapter starts at 87. This is also the page number in the TOC. I can't see anything abnormal here.

**Comment by kulla** [comment]
My bad... Everythings seems to be alright :-)
