### ISSUE TITLE
Content of the last page is streched to the end

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#124]
Example:

![screenshot from 2017-12-19 18-09-39](https://user-images.githubusercontent.com/1327215/34169489-dbfcd50a-e4e7-11e7-8df6-6da04126fc36.png)

The content is stretched to the end of the page which shouldn't be the case.

**Comment by Lodifice** [comment]
Thanks for pointing that out, fixed in  56cdbe5!
