### ISSUE TITLE
Create traffic statistic for mathe-builds.serlo.org

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#127]
We currently have the link https://mathe-builds.serlo.org/download/analysis1/analysis1.pdf which redirects to the real PDF. We need to analysis the logs in order to get the number of downloads / a download statistic.

**Comment by vroland** [comment]
The current statistic is `zcat /var/log/nginx/access.log*.gz | cat /var/log/nginx/access.log | cat /var/log/nginx/access.log | grep -i /download/analysis1/analysis1.pdf | wc -l` ... 
But goaccess https://goaccess.io/features looks promising.

**Comment by vroland** [comment]
done.
