### ISSUE TITLE
Parse and output definition lists

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#13]
Definition lists have the syntax

    ; label
    : definition
    ; label2
    : definition2

In HTML these are translated in `<dl><dt>...</dt><dd>...</dd>...</dl>`. This need to be parsed and properly output in latex. They occur for example in https://de.wikibooks.org/wiki/Mathe_f%C3%BCr_Nicht-Freaks:_Grenzwert:_Konvergenz_und_Divergenz#Definition_des_Grenzwerts

**Comment by Lodifice** [comment]
Implemented in 20a670976d8652e77b514da083f24a176c53ae52.
