### ISSUE TITLE
build diagnostics for referencial integrity

### ISSUE THREAD

**Issue by vroland** [Lodifice/mfnf-pdf-export#135]
When implementing better handling for internal references, I noticed many internal links are not valid any more. Many of those are referring to old anchors.

**Comment by kulla** [comment]
Is there an HTML page showing those malfunctioning links?

**Comment by vroland** [comment]
https://mathe-builds.serlo.org/nightly/Benutzer%40COLON%40Valentin_Roland%40SLASH%40Analysis_1/861124/stats/verbose/861124.stats.html

See `unresolved references`. I still have to test wether self-references (`[[#anker:bla]]`) do work, but actually I'd like to deprecate them, too in favor of full references (`[[Mfnf: ...#anker:bla]]`).

**Comment by kulla** [comment]
I have fixed the remaining mailfunctioned references.

**Comment by vroland** [comment]
nice!
