### ISSUE TITLE
Page 10 & 11 in prelude_a5 are blury

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#143]
![2018-11-22-095737_550x713_scrot](https://user-images.githubusercontent.com/1327215/48891980-30909e80-ee3d-11e8-833b-48e53e4f40f1.png)

**Comment by elbotho** [comment]
ok this is solved in https://github.com/Lodifice/mfnf-pdf-export/tree/a5-pdfs.

**Comment by vroland** [comment]
Thanks for fixing!
