### ISSUE TITLE
New print spec page [[Mathe für Nicht-Freaks: Print specification]]

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#150]
The page https://de.wikibooks.org/wiki/Mathe_f%C3%BCr_Nicht-Freaks:_Projekte/LMU_Buchprojekte was moved to https://de.wikibooks.org/wiki/Mathe_f%C3%BCr_Nicht-Freaks:_Print_specification Therefore the url in the tool need to be updated and deployed before the old page can be deleted.

**Comment by vroland** [comment]
@kulla This print specification is currently still in old format. 
Nightly builds are exported from https://de.wikibooks.org/wiki/Benutzer:Valentin_Roland/Analysis_1.
So as of now, the page can safely be moved, but the sitemap should be adapted to the new format at some point.

**Comment by kulla** [comment]
Dank dir. Habe das neue Format in https://de.wikibooks.org/wiki/Mathe_f%C3%BCr_Nicht-Freaks:_Print_specification eingefügt. Passt das so?

**Comment by vroland** [comment]
@kulla Ist geändert, es wird jetzt nach https://mathe-builds.serlo.org/nightly/Mathe_f%C3%BCr_Nicht-Freaks%40COLON%40_Print_specification/ exportiert. Da müsste man noch den Link auf Wikibooks anpassen, dann ist fertig :)

**Comment by kulla** [comment]
Endlich erledigt :-)
