### ISSUE TITLE
Parse and output links

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#16]
Links like `<a href="...">...</a>` need to be parsed and output to latex.

**Comment by vroland** [comment]
Added link parsing and output. We should discuss wether it makes sense to leave links to MFNF or to replace them with cross-references to the pdf.

**Comment by vroland** [comment]
Also, where should the documentation go? In html-inline the test expects a {"type": "elemen", ...}-like structure.

**Comment by kulla** [comment]
Cross-references inside the PDF will be more complicate to implement (since we need to track whether the linked content will be in the PDF) and we will need to output `\label` statements in the final `.tex` file. For printing this feature is not relevant and thus we do not need to implement it now. I have created #22

**Comment by kulla** [comment]
For the specification: The MediaWiki syntax shall be used here. See e094cae

**Comment by kulla** [comment]
IMHO the current state of link parsing and printing is sufficient for the first version of the pdf-exporter. We have https://github.com/Lodifice/mfnf-pdf-export/issues/22 and #23 for tracking the remaining issues.
