### ISSUE TITLE
example chapter for export tests

### ISSUE THREAD

**Issue by elbotho** [Lodifice/mfnf-pdf-export#19]
Task: Include an example chapter featuring all different content elements here:
https://de.wikibooks.org/wiki/Mathe_f%C3%BCr_Nicht-Freaks:_Projekte/LMU_Buchprojekte

The idea is to use that for technical and design testing.

**Comment by kulla** [comment]
I have created example chapters at https://de.wikibooks.org/wiki/Mathe_f%C3%BCr_Nicht-Freaks:_Beispielkapitel:_Grundlegende_Formatierungen#Kursiv.2C_Fett.2C_dfn.2C_Referenzen.2C_Links and https://de.wikibooks.org/wiki/Mathe_für_Nicht-Freaks:_Beispielkapitel:_Semantische_Blöcke

**Comment by kulla** [comment]
There is currently a `beispielbuch.pdf` created at https://homepages.physik.uni-muenchen.de/~Stephan.Kulla/mfnf-pdf-export/beispielbuch/beispielbuch.pdf

@elbotho Please reopen this issue in case you miss something
