### ISSUE TITLE
design-bundle-1: fonts and colors

### ISSUE THREAD

**Issue by elbotho** [Lodifice/mfnf-pdf-export#21]
### Colors
Color for headings, formulas(try for now):

**Serlo Blau** 
`#007EC1`

----

### Fonts
Font for everything but the Formulas: [Karmilla](https://github.com/ms-studio/karmilla)
We should use the TTF (no postscript, looks better I read).
Options: 
- put some effort in so that it works with pdflatex ( **Instructions:** [1](http://c.caignaert.free.fr/Install-ttf-Font.pdf), [2](http://xpt.sourceforge.net/techdocs/language/latex/latex33-LaTeXAndTrueTypeFont/ar01s02.html), [3](http://william.famille-blum.org/software/latexttf/index.html), [4](http://www.radamir.com/tex/ttf-tex.htm) )
- or switch to XeLaTex or LuaLaTex

----

### Code
I prototyped it with this code
``` tex
\usepackage{fontspec}
\setmainfont[Ligatures=TeX]{Karmilla-Regular.ttf}

\usepackage{sectsty}% http://ctan.org/pkg/sectsty
\usepackage{xcolor}% http://ctan.org/pkg/xcolor

\definecolor{sblau}{HTML}{007ec1}
\allsectionsfont{\color{sblau}}
```
----

### Screenshot
This is what it should look like :)
![image](https://user-images.githubusercontent.com/1258870/29926272-3f41ea14-8e63-11e7-8333-525ff242e250.png)

**Comment by elbotho** [comment]
- [ ] I need to add the german character `ß` in italic so we can use the italics as well!

**Comment by Lodifice** [comment]
Implemented in e020048e09e9e8fd64dc1332e7e24aa62b29f4ac. We switch to `lualatex` in e5c6c4b0e7dcfa083eaecdd1c00a8e93f2a4d234. @elbotho if you think everything regarding this issue is done, please close it. For new design suggestions, open a new issue.

**Comment by Lodifice** [comment]
I just saw that bold text is not rendered, I will work on that (it's easy).

More important: list bullets are not visible! Are they missing in Karmilla, too?

**Comment by Lodifice** [comment]
Added bold font in 2350919.

**Comment by elbotho** [comment]
Great! Added the Bullet Points to my todo list.
