### ISSUE TITLE
Design links inside the PDF

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#23]
Currently we hide links inside the PDF since those cannot be printed. However, in the long we need to decide how we want to display links inside a PDF.

**Comment by Lodifice** [comment]
A cool idea I have seen in someone's doctoral thesis is to put footnotes on the side and print a QR code pointing to the website there.

Is this also an option for us?

**Comment by kulla** [comment]
At least for videos this is a good option.

**Comment by elbotho** [comment]
I think if we focus on the pdf version a thumbnail with a link next to the text would be a bit better for the users. Can we access the video-thumbail?
The QR code idea could work nicely in the printed version.

**Comment by kulla** [comment]
@elbotho It is possible to get a thumbnail image. However I would delete all videos in the first version of the PDF exporter.

**Comment by vroland** [comment]
Is this still relevant or are qr codes for videos enough?

**Comment by kulla** [comment]
QR codes for videos are enough.
