### ISSUE TITLE
Compute the list of all authors of an article

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#3]
The CC-BY-SA license of our textbook project demands that we name all contributors of an article. Thus we need code which returns the list of all authors for an article. Spec:

* Input: Title of an article like [`Mathe für Nicht-Freaks: Vollständige Induktion`]( https://de.wikibooks.org/wiki/Mathe_f%C3%BCr_Nicht-Freaks:_Vollst%C3%A4ndige_Induktion)
* Output: List of the authors (user names like `Stephan Kulla`) together with a weight for how much thei contributed to the final article (for example the total number of bytes they have added to the article). The [history of the article](https://de.wikibooks.org/w/index.php?title=Mathe_f%C3%BCr_Nicht-Freaks:_Vollst%C3%A4ndige_Induktion&action=history) can be used.

For accessing the data the [MediaWiki API](https://www.mediawiki.org/wiki/API:Main_page) can be used. Namely https://www.mediawiki.org/wiki/Special:MyLanguage/API:Allrevisions

**Comment by vroland** [comment]
Should IP addresses be ignored or processed in any way?

**Comment by vroland** [comment]
A dict of authors and their contribution in bytes is now generated in the article parser. Ip addresses are counted as "anonymous" (maybe a better ipv6 regex is required). Now we have to think about a suitable way of representing them. Maybe a footnote for every article heading with a list of authors sorted by contributed size?

**Comment by kulla** [comment]
IP addresses can be ignored in the first version...

**Comment by kulla** [comment]
There is a first functioning output of authors which is sufficient. #34 and #35 for followup issues.
