### ISSUE TITLE
Download PNG files of SVGs in a high resolution

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#30]
PNG files of SVGs need to be downloaded in a high resolution for the print version.

**Comment by elbotho** [comment]
Not sure I understand. PDF files are capable of handling vector graphics, why would you convert to PNG?

**Comment by vroland** [comment]
Actually, svg files are not handled properly by pdflatex. Including .ps or .eps word fine, but svg does not, unfortunately. So we could include a conversion step from svg to eps in the makefile or just use png for now.

**Comment by vroland** [comment]
Although this might actually be easier than finding the correct link and also leads to a smaler pdf file.

**Comment by vroland** [comment]
@kulla @elbotho Have a look at the svgimages branch. It uses inkscape to convert to eps during the build process. I also had to remove the -no-shell-escape to allow pdflatex to build its pdf files. 
Now compare the image quality to master branch with thumbnails.

**Comment by vroland** [comment]
Images are directly converted to pdf now, so -no-shell-escape is re-added.

**Comment by elbotho** [comment]
@vroland klingt super!
hab aktuell keine umgebung zum testen.

**Comment by vroland** [comment]
I'll consider this as done.
