### ISSUE TITLE
Create table of contents

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#31]
In the final PDF a table of contents need to be created.

**Comment by Lodifice** [comment]
This was pretty pretty easy, see 976cec8.

The real question is: how should the toc be designed (@elbotho)? The style can be set directly via commands in the [latex_template.tex](../blob/master/mfnf/latex_template.tex).

**Comment by kulla** [comment]
I close this issue. For the design we have #33
