### ISSUE TITLE
Typeset proofs correctly

### ISSUE THREAD

**Issue by Lodifice** [Lodifice/mfnf-pdf-export#32]
Currently, we do not see "Beweis" and the number. The `\qed` at the end is not visible either.

**Comment by Lodifice** [comment]
As it appears, the standard `proof` environment is meant to only print "proof". If we pass the proof's name as an argument, the word "proof" is replaced with it.

Now we use the name of the theorem to be proven as the name of the proof. This is  natural, but also quite redundant. I see two options:
1. Do not use the name of the proof anymore, find out how to translate "proof" to "Beweis"
2. Define a new theorem "mfnf-proof"

Suggestions?

**Comment by kulla** [comment]
`\usepackage[ngerman]{babel}` fixes the problem :-)

**Comment by kulla** [comment]
Oh, I missread the issue... `\usepackage[ngerman]{babel}` only translates the word `proof`. However, I would vote for option (2).

**Comment by Lodifice** [comment]
I have implemented version one with a fixed proof environment in 5b0ed65c1544f3bc2db11beaac73a07c08c07b18. This fix is commonly found on Stackoverflow, e.g. https://tex.stackexchange.com/questions/179821/name-of-the-proof-instead-of-just-proof.
