### ISSUE TITLE
design: table of content

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#33]
Following issue of #31

**Comment by elbotho** [comment]
## New TOC design.
![image](https://user-images.githubusercontent.com/1258870/30388738-ebd33b96-98b0-11e7-9861-f3324d933138.png)
- leave out one hierarchy level
- no dotted lines
- no site numbers for parts
- …

----
To save space we could go with two rows (separated by blue 0.25pt line)
#### Quick mockup:
![image](https://user-images.githubusercontent.com/1258870/30388815-3781b572-98b1-11e7-8789-316212f923a3.png)

**Comment by Lodifice** [comment]
Implemented in a61f737. Please let me now what you think. The blue line as a separator ist still missing, but I think it does not look goog in two columns anyway (the page is just too narrow). We would have to shrink the text size to make it fit better.

**Comment by kulla** [comment]
@elbotho The table of contents is quite full. Can we decrease the font size?
![2017-09-18-205558_426x604_scrot](https://user-images.githubusercontent.com/1327215/30559133-e1396fc8-9cb3-11e7-892e-8c4c76f8982f.png)

**Comment by elbotho** [comment]
@kulla could you send me or upload the pdf file for that?

**Comment by elbotho** [comment]
@kulla added font size overview in #78.
TOC should all be set in 9pt.

**Comment by elbotho** [comment]
(this also depends on the amount of content that is selected…)

**Comment by Lodifice** [comment]
Font size is 9pt. I added the blue separator in 7210ce42785a850e4a20d35aa5ca51e4f194a245.

**Comment by elbotho** [comment]
Sorry for asking this now, but since we have a lot less content now:
Could we try to use a single column and no separator?

**Comment by elbotho** [comment]
And here some funny things happen:
![image](https://user-images.githubusercontent.com/1258870/31022108-18493dea-a538-11e7-9c85-2b1cd981a184.png)

**Comment by Lodifice** [comment]
Yes, we can easily go back.

I would just wait until we have decided the Part/Subsubsection thing. If we reverted, the design would also automatically be correct again (parts don't have a page number; dotted lines start from sections downwards).

The funny thing is a switch enabled by @kulla which shows overfull hboxes, so no need to worry there :D

**Comment by Lodifice** [comment]
Done in 6ae5629218d9b0ceaf5736d7552bcbe4ad72fecb.
