### ISSUE TITLE
Activate travis for this repository

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#39]
@Lodifice Travis works fine for we (see https://travis-ci.org/kulla/mfnf-pdf-export ). With it we have a continuous integrations system checking our unit tests at each `git push`. In order to activate it, you need to login at https://travis-ci.org/auth and to activate travis for this repository. See https://docs.travis-ci.com/user/getting-started/ for more details.

**Comment by kulla** [comment]
@Lodifice This is a small issue for enhancing the project. Do you think you can implement this issue in milestone 1.1?

**Comment by Lodifice** [comment]
I added the repo, look [here](https://travis-ci.org/Lodifice/mfnf-pdf-export). Of course, we had a build error due to some 504 server error ;)

The `.travis.yaml` was already added by you.
