### ISSUE TITLE
Images: Return license and contributors

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#4]
For each image we have in the textbook we need to compute some informations. Thus we need code which computes given the image name like [`Domino Cascade.JPG`](https://commons.wikimedia.org/wiki/File:Domino_Cascade.JPG) the following:

* License name: `Creative Commons Attribution 2.0 Generic`
* Link to the license: `https://creativecommons.org/licenses/by/2.0/deed.en`
* Link to image: `https://commons.wikimedia.org/wiki/File:Domino_Cascade.JPG`
* List of contributors (user who have uploaded image versions): `["Nauticashades"]`
* Author information: `aussiegall`
* Source information: `http://flickr.com/photos/14516334@N00/297237720`

**Comment by kulla** [comment]
@vroland After https://github.com/Lodifice/mfnf-pdf-export/commit/43abf883f14a8c52ead16587714143eab87aa3da `make test` returns an error. Can you update the specifications under `docs`?

**Comment by vroland** [comment]
Any thoughts on how to actually output this?

**Comment by elbotho** [comment]
@vroland  you mean visually?
@kulla is this meant to be displayed for each picture or as a list in the end of the book?

**Comment by vroland** [comment]
@kulla suggest a table of figures.
Make all pictures figures?
Table of figures (per article) might address pictures implicitly by their Order.

**Comment by vroland** [comment]
As tests are passing now and any changes regarding the design of the list of figures should be regarded as a separate issue in my opinion, I am finally closing this.
