### ISSUE TITLE
Do not cache parser errors

### ISSUE THREAD

**Issue by vroland** [Lodifice/mfnf-pdf-export#40]
If we want to run mfnf-pdf-export over night in an unattended fashion, we need to make sure to handle errors returned by the API corrently. I had an connection dropped response cached for some inline math, causing the make script to fail every time unitl I reset the cache. When leaving this to run overnight, the parser should maybe try to re-establish the connection a number of times before reporting an error.

**Comment by kulla** [comment]
Had the some problem some times... See also https://www.mediawiki.org/wiki/API:Errors_and_warnings

**Comment by kulla** [comment]
First implementation https://github.com/Lodifice/mfnf-pdf-export/commit/45c430f84b470f51b090d361430631ac00fdb851

**Comment by kulla** [comment]
Should be fixed now...
