### ISSUE TITLE
How to handle inline images

### ISSUE THREAD

**Issue by vroland** [Lodifice/mfnf-pdf-export#41]
Currently inline images are igored with an error. Is this how it should be gererally handled? Maybe just setting the image height to \lineheight might work, for example in https://de.wikibooks.org/wiki/Mathe_f%C3%BCr_Nicht-Freaks:_Intervall.

**Comment by kulla** [comment]
Yes, it is a bug to output an error. Some of the inline images are smileys via https://de.wikibooks.org/wiki/Vorlage:Smiley which can be handeled seperately...

**Comment by vroland** [comment]
As there are not that many cases of inline images, just displaying them with with the line height might be fine. (64c13f0062fd5b002dba050963a3d7aa52d5ab72)

**Comment by vroland** [comment]
@kulla @Lodifice @elbotho Do you think this implementation is enough for the 1.0 milestone?

**Comment by kulla** [comment]
@vroland Good for me :smile:
