### ISSUE TITLE
Handle Vorlage:Smiley

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#42]
Handle and output `{{Smiley}}` which includes a smiley (see https://de.wikibooks.org/wiki/Vorlage:Smiley ). This issue partly solves #41

**Comment by kulla** [comment]
@vroland For a first implementation in milestone 1.0 I would use `\smiley{}` and `\frownie{}`. See https://tex.stackexchange.com/q/3695

**Comment by elbotho** [comment]
I like them black and white :)

**Comment by vroland** [comment]
Or we could just use a font like DejaVu Sans as suggested there, as these would propably fit the text flow better. I will just test this for now.
