### ISSUE TITLE
Add the possibility to only exclude certain sections of an article

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#49]

**Comment by Lodifice** [comment]
Isn't this solved by 4c3ecad1c5ef30033615f669f7ba691e62cce0e6? What is missing?

**Comment by kulla** [comment]
Excluding of titles like `Header <math>x^2</math>` is not possible yet...

**Comment by kulla** [comment]
Actually I haven't forgotten this issue :smile:
