### ISSUE TITLE
Parse from headings sections

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#50]
Instead of the tree

    - type: header
      depth: 1
      content: [type: text, data: "Foo"]
    - type: paragraph
      content: [type: text, data: "Hello World"]
    - type: header
      depth: 2
      content: [type: text, data: "Bar"]
    - type: paragraph
      content: [type: text, data: "12 34 56"]

We need to have the parsing tree in form of

    - type: section
      title: [type: text, data: "Foo"]
      content:
        - type: paragraph
         content: [type: text, data: "Hello World"]
        - type: section
          depth: 2
          title: [type: text, data: "Bar"]
          content:
            - type: paragraph
              content: [type: text, data: "12 34 56"]

Background: We need to include only some parts of an atricle and there need to be a way to delete certain sections of an article. See #48 and #49

**Comment by Lodifice** [comment]
Implemented in 4af63c3c19b46f634e7391ddce37591edc9223a9.
