### ISSUE TITLE
Parsing and output of &nbsp;

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#52]
`&nbsp;` need to be parsed and output. It is parsed to HTML with

    <span typeof="mw:Entity" id="mwAg"> </span>

**Comment by kulla** [comment]
My suggestion for parsing type:

    { "type": "entity", "kind": " " }

**Comment by Lodifice** [comment]
Implemented in 2075b7d682869641c47fe59bdb228b0f7f66df42. Although I did not find any in the analysis1 book, @kulla?

**Comment by kulla** [comment]
@Lodifice The id's of HTML elements are always randomly generated...
