### ISSUE TITLE
Missing Characters in Karmilla Font

### ISSUE THREAD

**Issue by elbotho** [Lodifice/mfnf-pdf-export#55]
Some characters missing, will add them to [Karmilla](https://github.com/ms-studio/karmilla) 

- [x] `ß` in in italics
- [x] bullet points (Unicode: 2022)
- [ ] investigate missing "sl"-shapes

```
Missing character: There is no • (U+2022) in font [../../karmilla/ttf/Karmilla
-Regular-016.ttf]:mode=node;+tlig;!
-----
LaTeX Font Warning: Font shape `TU/Karmilla-Regular-016(0)/m/sl' undefined
(Font)              using `TU/Karmilla-Regular-016(0)/m/n' instead on input line
 91.
```

**Comment by vroland** [comment]
If possible, I would like to use unicode smileys for the output of #42, but Karmilla does not seem to support any. Any thoughts about using unicode smileys like these: https://unicode-table.com/en/blocks/emoticons/ ?

**Comment by elbotho** [comment]
as I understand only a few fonts support colored unicode smileys.

Github for example uses this Fontstack: "Apple Color Emoji", "Segoe UI", "Segoe UI Emoji", "Segoe UI Symbol"

**Comment by elbotho** [comment]
@vroland please try those updated fonts. they include bullet points and a new italic shape.
[Karmilla-016m.zip](https://github.com/Lodifice/mfnf-pdf-export/files/1306158/Karmilla-016m.zip)

**Comment by elbotho** [comment]
If the slanted warning is still occurring: here is a solution:
https://tex.stackexchange.com/questions/273133/latex-font-warning-font-shape-undefined

**Comment by kulla** [comment]
@elbotho Can you make a fork of https://github.com/ms-studio/karmilla and and your new created fonts there? We include karmilla as a git submodule and this makes it easier to update the fonts (you can also make a merge request afterwards).

**Comment by elbotho** [comment]
right! current version with ß and bullets is here:

https://github.com/elbotho/karmilla

**Comment by Lodifice** [comment]
Your version is used as of 07e0b578541771692a42c1c117062def1477aa55. I don't see a warning regarding slanted anymore. In the log it says it found no slanted font and used italic instead.

From my perspective, we can close this issue.

**Comment by elbotho** [comment]
nice!
I'll just reopen if needed.
