### ISSUE TITLE
Add sha1 of image to its file name

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#56]
After #51 we do not download when a file have changed. Thus we should add the SHA1 of the image to its file name. So we would download a new version of an image after its upload.

**Comment by vroland** [comment]
fixed in fcbf6edcf4ebe90385778ca316f76f43d3f46301.

**Comment by vroland** [comment]
Still have to adjust the download function...

**Comment by kulla** [comment]
I want to use https://www.mediawiki.org/wiki/API:Imageinfo where the sha1 of an image can be queried. Thus I reopen this issue (it is not urgent to implement this enhancement)

**Comment by vroland** [comment]
Thix is already implemented in 4666faea610b3b6f8c479e4b31762ef7e1cd12aa. Not sure why it is not showing closed from...

**Comment by kulla** [comment]
@vroland See https://github.com/Lodifice/mfnf-pdf-export/issues/56#issuecomment-330136706

**Comment by vroland** [comment]
This is what I mean. The hash is queried via the imageinfo API since 4666fae ? What do I overlook?

**Comment by kulla** [comment]
Oh, my mistake. I haven't seen the new commit :see_no_evil:
