### ISSUE TITLE
design: Decide which format to use

### ISSUE THREAD

**Issue by elbotho** [Lodifice/mfnf-pdf-export#60]
Possible Formats (_in mm_):
``` python
148 * 210   # A5
155 * 235   # <- favourite
170 * 240      
210 * 297   # A4
```

**Comment by vroland** [comment]
How could we handle overly wide formulas like in 2.0.15
Einbindbare Inhalte in the example book? Is there a nice solution without increasing paper size?

**Comment by kulla** [comment]
@vroland They need to be fixed by hand through the authors (which is a good thing because those formulas do not work on mobile devices, too)

**Comment by elbotho** [comment]
there seem to be options to scale formulas that we could look into.
e.g. [here](https://stackoverflow.com/questions/3106587/scale-an-equation-to-fit-exact-page-width) or [here](https://tex.stackexchange.com/questions/35554/how-can-i-auto-adjust-a-equation-to-appear-in-the-entire-page-scale-to-equatio).

**Comment by kulla** [comment]
I have opened #73 for the question about handling too wide formulas...

**Comment by kulla** [comment]
Decision made on friday: 155mm * 235mm will be our format.
