### ISSUE TITLE
design: important paragraphs

### ISSUE THREAD

**Issue by elbotho** [Lodifice/mfnf-pdf-export#62]
- Important paragraphs should be indented (11pt atm. – just like the line height)
- the blue bar next to them is half the width (5.5pt) and also `#007EC1` in 35% intensity (or `#b2d9ea` absolute)

#### Mockup
![image](https://user-images.githubusercontent.com/1258870/30438603-eb4c26f8-9971-11e7-8aed-f6fe3051850e.png)

**Comment by Lodifice** [comment]
Implemented in c75627f.
