### ISSUE TITLE
design: lists

### ISSUE THREAD

**Issue by elbotho** [Lodifice/mfnf-pdf-export#63]
Indentation should be the same for all list items.

Like for #62 the indentation is set at 11pt atm.

Bullets will be added when i finish #55.

#### Mockup
![image](https://user-images.githubusercontent.com/1258870/30439292-a6b0042c-9973-11e7-9716-32e090374998.png)

**Comment by Lodifice** [comment]
Implemented in 952b6ce041788c7108393fb8ae442e6490d93ed8. I don't know if nested lists become an issue. If so, please reopen (it's easy for me to fix).
