### ISSUE TITLE
design: images, figures, galleries

### ISSUE THREAD

**Issue by elbotho** [Lodifice/mfnf-pdf-export#64]
*`aside-images`*
- … and gallery images should be contained in boxes of the same width.
- …should be fixed in width and set a calculated height.

*`gallery-images`*
- are scaled to fill the surrounding box.
- The box is not square, but a bit wider than high.

*`content-images`*
- should a maximum height be never be wider as the text.
- smaller images (less complexity) should display smaller.

Let's see how it works out! :)

#### Mockup: Figures and single images
![image](https://user-images.githubusercontent.com/1258870/30439542-5ee63624-9974-11e7-82dc-6a7c6f38b85a.png)

#### Mockup: Galleries
![image](https://user-images.githubusercontent.com/1258870/30439750-e5bd3742-9974-11e7-801a-50f272370e51.png)

**Comment by vroland** [comment]
Grey background for images is probably not feasable for now, as some images have a white background themselves.

**Comment by vroland** [comment]
@Lodifice @kulla There seem to be some glitches if a highlighted paragraph is next to a thumbnail image on even pages. (for example in the Stetigkeit article, currently page 634 of analysis1.pdf). Does anyone of you know why?

**Comment by vroland** [comment]
I suggest to implement thumnail pictures as galleries under the last lowest-level heading, because of the limitations of wrapping figures described in #96. Since LaTeX works in Paragraphs, wrapping figures will never work properly with environments, which are used quite extensively throughout our TeX output.

**Comment by elbotho** [comment]
Background color issue moved to #66

@vroland looks good so far! 

## Improvement ideas

#### alignment
Could you set the texts to a *ragged alignment* (flattersatz)? 

I think it would work better to avoid cases like this
![image](https://user-images.githubusercontent.com/1258870/31332601-499bc08c-ace7-11e7-932a-f0f7ea0d8808.png)

#### position of content-images
Margin to top paragraph: too little
Margin to top paragraph: too much
![image](https://user-images.githubusercontent.com/1258870/31332843-35151040-ace8-11e7-946a-8195cc3e8a95.png)


#### size
Some Images seem to be to big.
![image](https://user-images.githubusercontent.com/1258870/31332693-ab8d579c-ace7-11e7-855a-4039465c81b8.png)

####
