### ISSUE TITLE
Avoid nesting of semantic blocks

### ISSUE THREAD

**Issue by Lodifice** [Lodifice/mfnf-pdf-export#69]
If semantic blocks are nested, the frame (i.e., the blue line to the left) is drawn twice. This does not only look ugly, but once we add icons, they will be placed on top of the line of the outer block.

An example is [here](https://de.wikibooks.org/wiki/Mathe_f%C3%BCr_Nicht-Freaks:_Folgenkriterium_der_Stetigkeit:_Folgenstetigkeit#Zusammenhang_zum_Epsilon-Delta-Kriterium) where an important paragraph is nested in a solution process (for some strange reason it inherits the frame title of the outer environment, but is otherwise typeset correctly - blue color).

**Comment by kulla** [comment]
Nested semantic boxes is an error and shall be replaced by `{type: error, message: ...} `

**Comment by kulla** [comment]
https://github.com/Lodifice/mfnf-pdf-export/commit/e19cd5b5c66a7bb8462eed702f4ad3ed43ad2f01 Should solve this issue...
