### ISSUE TITLE
String: childrentypeordered

### ISSUE THREAD

**Issue by elbotho** [Lodifice/mfnf-pdf-export#7]
In the current PDF export there are multiple occurrences of the String 
_childrentypeordered_

**Comment by elbotho** [comment]
![image](https://user-images.githubusercontent.com/1258870/29815103-c7e78ed8-8caf-11e7-869b-de95ff1ba223.png)

**Comment by kulla** [comment]
The bug was already fixed with https://github.com/Lodifice/mfnf-pdf-export/commit/0e35427e0ce807784a98ee2a213d6be5b4bf3d82 :-) Thanks for the reporting!
