### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by vroland** [Lodifice/mfnf-pdf-export#72]
There are several issues that need to be fixed by the authors, like fixing formulas or avoiding certain html elements. Currently, these issues are shown as errors in the build log with only the exerpt of the half-way parsed syntax tree, which is very confusing for people not familiar with this export software.
If possible, we should provide a way to locate the error and a more detailed error description.

**Comment by kulla** [comment]
@vroland Can this issue be closed?

**Comment by vroland** [comment]
I think this is ok for now, although this should always be at the back of our minds when writing the parser.
