### ISSUE TITLE
Followup of #68: Floating graphics in semantic blocks

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#74]
After https://github.com/Lodifice/mfnf-pdf-export/commit/e8c190495dea2235f44e4fb7e666995dad52bdbb we delete thumbnails inside semantic boxes. This is enough for milestone 1.0 but we need to find a better solution in the future...

**Comment by vroland** [comment]
Is  hoisting thumbnails to the closest heading (currently used in the nightlies) satisfactory here?

**Comment by kulla** [comment]
Yes, the current solution is satisfactory.
