### ISSUE TITLE
design: Typographic Scale

### ISSUE THREAD

**Issue by elbotho** [Lodifice/mfnf-pdf-export#78]
Let's try this. 

### Font sizes

The base font size should be 9pt. 
That's a bit small, but should work in the sans-serif font and saves a lot of pages.

The size scale is based on the "perfect fourth" (4/3 or 1.3333) and rounded for simplicity:
```
  9pt
  12pt
  16pt
~ 21pt
  28pt
~ 37pt
  44pt
  …
```

* Base font size: **9pt**
* Base line height: **12pt**
* Header "second level" : **9pt**
* Header "first level" *(1.0.1)*: **12pt**
* Chapter Headings: **21pt**
* Part Headings: **44pt**
* Title: **44pt**

### Line Height
Line height is always 133% (so 9pt gets a 12pt line height)

**Comment by kulla** [comment]
@elbotho For the record: LaTeX defines by default `baselineheight = 1.2 * basefontsize`.

**Comment by kulla** [comment]
For an info: I tried https://tex.stackexchange.com/a/103290/31701 but I had problems with it...

**Comment by Lodifice** [comment]
Set the sizes in bc7e8153ab7342257828233e192cd9d576f0d069. IMO parts and titles are way too large @elbotho - I will send a preview to you.
