### ISSUE TITLE
Parse and output {{-|...}}

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#8]
The following code need to be parsed:

    {{-|A paragraph}}

The template is already recognized. In the end this node can be represented by

    { "type": "importantparagraph", "content": ... }

For the final output the important paragraph need to be printed with an overall indent.

**Comment by vroland** [comment]
Done, but leaving the issue open until we have a better LaTeX translation for this. (indentation only does not look nice.)

**Comment by vroland** [comment]
Looks acceptable now.
