### ISSUE TITLE
Implement solutions for reducing the page number

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#85]
See http://www.tricider.com/brainstorming/3CmpEDLwUhp

- [x] hide "Verständnisfragen"
- [x] hide alternative proofs

This is an issue to track all actions taken...

**Comment by kulla** [comment]
We have reached our goal to reduce the page number to less than 350 pages :smile: New solution should be stored in new issues...

**Comment by vroland** [comment]
done for latex, so this is not relevant for the "new toolchain" milestone any more.
