### ISSUE TITLE
Find good values for BCOR and DIV

### ISSUE THREAD

**Issue by kulla** [Lodifice/mfnf-pdf-export#86]
See http://texdoc.net/texmf-dist/doc/latex/koma-script/scrguien.pdf for documentation of values.

**Comment by kulla** [comment]
@elbotho Is the margin around the text of an page okay?

**Comment by elbotho** [comment]
Suggestion in 60bd2ab
This is what I would set for now, but for the final BCOR value I want to talk to the selected printer to make sure.
