### ISSUE TITLE
Nested Boxes

### ISSUE THREAD

**Issue by elbotho** [Lodifice/mfnf-pdf-export#89]
In the export from two days ago (2017/09/27) there are sometimes nested boxes. 
I think they appear when Questions and Answers are used inside another box.

![image](https://user-images.githubusercontent.com/1258870/31008431-63a2c470-a504-11e7-89e1-9fab00af685a.png)

This is relating to #65.

**Comment by Lodifice** [comment]
The implementation of e19cd5b5c66a7bb8462eed702f4ad3ed43ad2f01 was not sufficient, I fixed it in dde1e9f92905e490302020bc7b9300f89ca7e3e1.

Now the example you showed results in an error. @kulla can you please send information to the authors - they have to check their articles again ;)
