### ISSUE TITLE
Avoid overfull hboxes

### ISSUE THREAD

**Issue by matipau** [Lodifice/mfnf-pdf-export#91]
TeX has problems breaking some of our paragraphs. This leads to overfull hboxes which look very ugly. Since we cannot change the text manually, we need other methods to avoid this. For example, we could increase the `\tolerance` or `\emergencystretch` parameter (see e.g. https://tex.stackexchange.com/questions/241343/what-is-the-meaning-of-fussy-sloppy-emergencystretch-tolerance-hbadness). And we could allow TeX to hyphenate words already containing a hyphen (see e.g. https://tex.stackexchange.com/questions/2706/adequate-hyphenation-of-words-already-containing-a-hyphen).

**Comment by kulla** [comment]
A possibility: statements with `\lim` in inline mode can be rendered as normal mode with reduces the width (and increases the height). `\sloppy` should be a better solution... :-)
