### ISSUE TITLE
Too little spacing between section titles and semantic boxes

### ISSUE THREAD

**Issue by matipau** [Lodifice/mfnf-pdf-export#92]
If a section or subsection immediately starts with a semantic box, there is much less spacing after the section or subsection title than if a paragraph would follow. Independently of #79, the spacing should be at least the same.
![mfnf-problem](https://user-images.githubusercontent.com/29919872/31045534-19dd4d8c-a5e6-11e7-931f-310de8329355.png)

**Comment by elbotho** [comment]
Thank you for pointing that out. I ran into problems while trying to change the spacings because of this.

**Comment by Lodifice** [comment]
This seams to be an internal issue in mdframed (look [here](https://tex.stackexchange.com/questions/251487/erratic-behavior-of-mdframed-environment-right-after-headings)). I fixed it using `startcode=\leavevmode` in b6db383b7aa4c25b410a8b7242ccd32e644a24fb, but we might be better with switching to `tcolorbox` in the future (if similar issues occur).
