### ISSUE TITLE
Add predesigned pages

### ISSUE THREAD

**Issue by elbotho** [Lodifice/mfnf-pdf-export#94]
We need a possibility to add pages that are designed independently of the latex export. 
(Let's call them "meta-pages" like: "About the Project" etc. but also the cover, imprint etc.)
I will provide them as PDF files.

**Technical options**
- A: Split the LaTex export into single PDFs and join als PDFs together afterwards
- B: Import premade PDF pages into the LaTeX project

**Possible problems**
- Page numbers could pose a problem. We discussed that we could use the numbering only in the generated content. Option B might be the better solution in this case.

- TOC: Do we want to have the meta pages in the TOC at all?

**Comment by Lodifice** [comment]
I opt for option B, using [pdfpages](http://mirror.physik-pool.tu-berlin.de/tex-archive/macros/latex/contrib/pdfpages/pdfpages.pdf). They even have an option to include the pages into the TOC!

**Comment by elbotho** [comment]
Sounds perfect!

**Comment by elbotho** [comment]
Will provide example PDF

**Comment by elbotho** [comment]
example pdf file with trim.
[mfnf_example_import_wtrim.pdf](https://github.com/Lodifice/mfnf-pdf-export/files/1375421/mfnf_example_import_wtrim.pdf)

**Comment by Lodifice** [comment]
I have included the examples in 2e8f9c2. @elbotho please have a look, the included pages to not really fit our geometry.

Note that you will only see the first page of the included PDF repeated. This is because of `\usepackage[Export]{adjustbox}`. The issue is known, see [stackoverflow](https://tex.stackexchange.com/questions/195521/adjustbox-with-export-option-seems-to-break-page-selection-in-pdfpages). @kulla you have added the use of that package in 425d9ae67c7ebc784c6b63c223df88836ebf2a43. Is it possible to modify your code like in the linked article?

**Comment by elbotho** [comment]
@Lodifice As mentioned they include trim(3mm) on all sides and therefore result in a different format. The white borders don't make sense to me.
Might be fixed with #99.

**Comment by elbotho** [comment]
Second PDF mockup
[mfnf_example_import_after.pdf](https://github.com/Lodifice/mfnf-pdf-export/files/1401505/mfnf_example_import_after.pdf)

@Lodifice does your implementation depend on a fixed number of pages? Or does it add all the pages automatically?

**Comment by Lodifice** [comment]
Fixed the `Export` issue in 5a23d042d4a1e7102f59b5dc3997316965ae46b6.

As of 99d53265c44c2c3cd995b615ec0c3b06fcd828b4, there are two included PDFs in the `predesigned_pages` directory:
* `mfnf_prelude.pdf` is inserted in the beginning, before title page and toc
* `mfnf_epilogue.pdf` is inserted in the end, after the list of figures

@elbotho the number of pages is not relevant, all are inserted. The counting of the internal document starts afterwards. However, it does not seem possible to add the epilogue to the toc (at least I can't get it to work).

**Comment by elbotho** [comment]
👍  looks good to me!
will open new issue if we need another insert / changes.
