### ISSUE TITLE
design: Part title pages

### ISSUE THREAD

**Issue by elbotho** [Lodifice/mfnf-pdf-export#97]
Font sizes: 44pt and 9pt
Font weight: all bold but the "Autoren und Autorinnen" title (See closeup)

Author names can really pile up so if LaTeX allows they should be positioned relative to the bottom.
(distance from last line to the bottom should always be the same even if there are a lot of authors)

#### mockup
![image](https://user-images.githubusercontent.com/1258870/31269747-dcf256a6-aa81-11e7-875e-28916743b7a8.png)

#### closeup
![image](https://user-images.githubusercontent.com/1258870/31269697-b5599d2a-aa81-11e7-921e-8eb9cf96da14.png)

**Comment by Lodifice** [comment]
Implemented in b8a6279. I used the Serlo light blue (Serlo blue at 15 %) which is way too bright in my opinion.

@elbotho can you please have a look and provide an appropriate color code?

**Comment by elbotho** [comment]
Sorry, missed that.
I used `35%` above.

**Comment by Lodifice** [comment]
Fixed in  01998fa.

Now it looks enjoyable ;)
