### ISSUE TITLE
Find a way to implement page trim in latex.

### ISSUE THREAD

**Issue by vroland** [Lodifice/mfnf-pdf-export#99]

**Comment by vroland** [comment]
@elbotho https://mike42.me/blog/2016-01-how-to-arrange-pages-for-printing-and-cutting-in-latex is this part of what you are looking for?

**Comment by elbotho** [comment]
This is quite a bit more complex than what we need I think.

We just need "3mm more" on each side of the page. (3mm is a guess until we know the printers requirements)

Answer should hide somewhere here:
https://tex.stackexchange.com/questions/181078/crop-and-bleed-marks
https://tex.stackexchange.com/questions/65170/what-is-bleed-and-how-do-i-achieve-it/65199#65199
https://tex.stackexchange.com/questions/19497/how-do-you-setup-a-tex-document-to-self-publish-a-book-online/130843#130843

**Comment by elbotho** [comment]
This seems to work, so we can close it?

**Comment by vroland** [comment]
I think you are the one to decide that ;)

**Comment by elbotho** [comment]
I remove page trim again for now.
Does not make sense for the downloadable version, will add manually for print-export or enable export with different settings like discussed in #120

(see 0a4c677fa92df2ead25e2eab9af9f47aeb579455)

**Comment by kulla** [comment]
@elbotho what is the status for the LMU wide print?

**Comment by elbotho** [comment]
done as far as I can tell
